export enum DocType  {
    BenefitsManagementApproach = "Benefits Management Approach",
    BusinessCase = "Business Case",
    ChangeControlApproach = "Change Control Approach",
    CheckpointReport = "Checkpoint Report",
    CommunicationManagementApproach = "Communication Management Approach",
    ConfigurationItemRecord = "ConfigurationItemRecord",
    DailyLog = "Daily Log",
    EndProjectReport = "End Project Report",
    EndStageReport = "End Stage Report",
    ExceptionReport = "Exception Report",
    HighlightReport = "Highlight Report",
    IssueRegister = "Issue Register",
    IssueReport = "Issue Report",
    LessonsLog = "Lessons Log",
    LessonsReport = "Lessons Report",
    Plan = "Plan",
    ProductDescription = "Product Description",
    ProductStatusAccount = "Product Status Account",
    ProjectBrief = "Project Brief",
    ProjectInitiationDocumentation = "Project Initiation Documentation",
    ProjectProductDescription = "Project Product Description",
    QualityManagementApproach = "Quality Management Approach",
    QualityRegister = "Quality Register",
    RiskManagementApproach = "Risk Management Approach",
    RiskRegister = "Risk Register",
    WorkPackage = "Work Package"
}